import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"

import { cn } from "@/lib/utils"

const inter = Poppins({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased bg-zinc-50 text-white",
          inter.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
